# Generated by Django 3.1.5 on 2021-03-26 22:18

from django.db import migrations

from data.utils import trunc_normal


def example_data_fix(apps, schema_editor):
    # Example Data is created in 0006_example_data with old reference values
    # and via bulk_create which doesn't perform model validation.
    # As these reference values changed (validations), the
    # data has invalid fields with the current validations which needs to
    # be fixed. As this is dummy data they will be just re-created.
    Data = apps.get_model("data", "Data")
    data = Data.objects.filter(unit__name__icontains="(E)")
    for d in data:
        d.mchc = round(trunc_normal(2, 5, 3, 1, 1)[0])
        d.eo = trunc_normal(0, 10, 5, 2, 1)[0]
        d.igm = trunc_normal(10, 400, 50, 5, 1)[0]
        d.hct = trunc_normal(0.2, 0.8, 0.4, 0.2, 1)[0]
        d.lymp = (trunc_normal(0.1, 30, 8, 2, 1)[0]
                  if d.is_covid19 else trunc_normal(0.1, 30, 5, 2, 1)[0])
        d.neut = (trunc_normal(0.2, 40, 5, 2, 1)[0]
                  if d.is_covid19 else trunc_normal(0.2, 40, 8, 2, 1)[0])
        d.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_data_alter_uuid'),
    ]

    operations = [
        migrations.RunPython(
            example_data_fix,
            migrations.RunPython.noop
        )

    ]
